/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
https://github.com/NicabarNimble/plugin-vault-trace
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  TraceRegistry: () => TraceRegistry,
  default: () => TracePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian8 = require("obsidian");

// src/appendModal.ts
var import_obsidian = require("obsidian");

// reference/parser.ts
var FORMAT_TOKEN = "tracev1";
var GENESIS = "0000000000000000000000000000000000000000000000000000000000000000";
var REQUIRED_FRONTMATTER_KEYS = [
  "trace",
  "format",
  "trace_name",
  "trace_slug",
  "actor_name",
  "actor_slug",
  "actor_id"
];
var FIELD_SEPARATOR = " | ";
var RESERVED_TAGS = ["#genesis", "#rebaseline", "#attest", "#rotate"];
var SEQ_RE = /^(0|[1-9][0-9]*)$/;
var TIMESTAMP_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/;
var ACTOR_RE = /^[^|\\#\r\n ][^|\\\r\n]*$/;
var TAG_RE = /^#[a-z0-9][a-z0-9_-]*$/;
var TEXT_RE = /^(?:[^|\\\r\n]|\\[\\nr|])+$/;
var ANCHOR_RE = /^#[0-9a-f]{8}$/;
var SLUG_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
var SHA256_HEX_RE = /^[0-9a-f]{64}$/;
var ATTESTATION_VALUE_RE = /^(?:[A-Za-z0-9._~/-]|%[0-9A-F]{2})+$/;
function slugify(name) {
  let slug = name.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  if (slug.length > 60) {
    slug = slug.slice(0, 60).replace(/-+$/g, "");
  }
  return slug;
}
function isValidSlug(slug) {
  return slug.length > 0 && slug.length <= 60 && SLUG_RE.test(slug);
}
function encodeKeyValue(value) {
  return encodeURIComponent(value).replace(
    /[!'()*]/g,
    (ch) => "%" + ch.charCodeAt(0).toString(16).toUpperCase()
  ).replace(/%2F/g, "/");
}
function decodeKeyValue(value) {
  if (!ATTESTATION_VALUE_RE.test(value)) return null;
  try {
    const decoded = decodeURIComponent(value);
    return encodeKeyValue(decoded) === value ? decoded : null;
  } catch {
    return null;
  }
}
function formatAttestationPayload(payload) {
  if (payload.change === "rename") {
    return [
      `from=${encodeKeyValue(payload.from)}`,
      `to=${encodeKeyValue(payload.to)}`,
      "change=rename",
      `sha256=${payload.sha256}`
    ].join(" ");
  }
  const parts = [
    `path=${encodeKeyValue(payload.path)}`,
    `change=${payload.change}`
  ];
  if (payload.change !== "delete") parts.push(`sha256=${payload.sha256}`);
  return parts.join(" ");
}
function parseKeyValuePayload(text, label) {
  const fields = /* @__PURE__ */ new Map();
  for (const token of text.split(" ")) {
    if (token.length === 0) {
      return { ok: false, message: `empty token in ${label} payload` };
    }
    const eq = token.indexOf("=");
    if (eq <= 0 || eq === token.length - 1) {
      return { ok: false, message: `${label} token "${token}" is not key=value` };
    }
    const key = token.slice(0, eq);
    if (!/^[a-z][a-z0-9_]*$/.test(key)) {
      return { ok: false, message: `invalid ${label} key "${key}"` };
    }
    if (fields.has(key)) {
      return { ok: false, message: `duplicate ${label} key "${key}"` };
    }
    fields.set(key, token.slice(eq + 1));
  }
  return fields;
}
function requireEncodedValue(fields, key, label) {
  const raw = fields.get(key);
  if (raw === void 0) return { ok: false, message: `missing ${label} key "${key}"` };
  const decoded = decodeKeyValue(raw);
  if (decoded === null) return { ok: false, message: `invalid ${label} value for "${key}"` };
  return decoded;
}
function requireSha256(fields, key, label) {
  const sha = fields.get(key);
  if (sha === void 0) return { ok: false, message: `missing ${label} key "${key}"` };
  if (!SHA256_HEX_RE.test(sha)) {
    return { ok: false, message: `${label} ${key} must be 64 lowercase hex characters` };
  }
  return sha;
}
function onlyKeys(fields, keys, label) {
  for (const key of fields.keys()) {
    if (!keys.includes(key)) {
      return { ok: false, message: `unexpected ${label} key "${key}"` };
    }
  }
  return null;
}
function parseAttestationPayload(text) {
  const fields = parseKeyValuePayload(text, "attestation");
  if (!(fields instanceof Map)) return fields;
  const change = fields.get("change");
  if (change !== "create" && change !== "modify" && change !== "delete" && change !== "rename") {
    return { ok: false, message: "attestation change must be create, modify, delete, or rename" };
  }
  const canonical = (payload) => formatAttestationPayload(payload) === text ? { ok: true, payload } : {
    ok: false,
    message: "attestation payload must use canonical key order and encoding"
  };
  if (change === "rename") {
    const unexpected2 = onlyKeys(fields, ["from", "to", "change", "sha256"], "attestation");
    if (unexpected2) return unexpected2;
    const from = requireEncodedValue(fields, "from", "attestation");
    if (typeof from !== "string") return from;
    const to = requireEncodedValue(fields, "to", "attestation");
    if (typeof to !== "string") return to;
    const sha2562 = requireSha256(fields, "sha256", "attestation");
    if (typeof sha2562 !== "string") return sha2562;
    return canonical({ change, from, to, sha256: sha2562 });
  }
  const keys = change === "delete" ? ["path", "change"] : ["path", "change", "sha256"];
  const unexpected = onlyKeys(fields, keys, "attestation");
  if (unexpected) return unexpected;
  const path = requireEncodedValue(fields, "path", "attestation");
  if (typeof path !== "string") return path;
  if (change === "delete") return canonical({ change, path });
  const sha256 = requireSha256(fields, "sha256", "attestation");
  if (typeof sha256 !== "string") return sha256;
  return canonical({ change, path, sha256 });
}
function formatRotationPayload(payload) {
  return [
    `previous=${encodeKeyValue(payload.previous)}`,
    `previous_seq=${payload.previousSeq}`,
    `previous_head=${payload.previousHead}`
  ].join(" ");
}
function parseRotationPayload(text) {
  const fields = parseKeyValuePayload(text, "rotation");
  if (!(fields instanceof Map)) return fields;
  const unexpected = onlyKeys(fields, ["previous", "previous_seq", "previous_head"], "rotation");
  if (unexpected) return unexpected;
  const previous = requireEncodedValue(fields, "previous", "rotation");
  if (typeof previous !== "string") return previous;
  const previousSeqRaw = fields.get("previous_seq");
  if (!previousSeqRaw || !/^[1-9][0-9]*$/.test(previousSeqRaw)) {
    return { ok: false, message: "rotation previous_seq must be a positive integer" };
  }
  const previousHead = requireSha256(fields, "previous_head", "rotation");
  if (typeof previousHead !== "string") return previousHead;
  const payload = {
    previous,
    previousSeq: parseInt(previousSeqRaw, 10),
    previousHead
  };
  return formatRotationPayload(payload) === text ? { ok: true, payload } : {
    ok: false,
    message: "rotation payload must use canonical key order and encoding"
  };
}
function escapeText(text) {
  let out = "";
  for (const ch of text) {
    if (ch === "\\") out += "\\\\";
    else if (ch === "\n") out += "\\n";
    else if (ch === "\r") out += "\\r";
    else if (ch === "|") out += "\\|";
    else out += ch;
  }
  return out;
}
function unescapeText(escaped) {
  let out = "";
  for (let i = 0; i < escaped.length; i++) {
    const ch = escaped[i];
    if (ch !== "\\") {
      out += ch;
      continue;
    }
    const next = escaped[i + 1];
    if (next === "\\") out += "\\";
    else if (next === "n") out += "\n";
    else if (next === "r") out += "\r";
    else if (next === "|") out += "|";
    else return null;
    i++;
  }
  return out;
}
function canonicalize(fields) {
  return [
    String(fields.seq),
    fields.timestamp,
    fields.actor,
    fields.tag ?? "",
    escapeText(fields.text)
  ].join("|");
}
async function sha256Bytes(input) {
  const bytes = input instanceof Uint8Array ? input : new Uint8Array(input);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
}
async function sha256Hex(input) {
  return sha256Bytes(new TextEncoder().encode(input));
}
async function computeEntryHash(prevFullHash, fields) {
  return sha256Hex(prevFullHash + "\n" + canonicalize(fields));
}
function toAnchor(fullHash) {
  return fullHash.slice(0, 8);
}
function formatEntryLine(fields, fullHash) {
  const parts = [
    String(fields.seq),
    fields.timestamp,
    fields.actor
  ];
  if (fields.tag !== null) parts.push(fields.tag);
  parts.push(escapeText(fields.text), "#" + toAnchor(fullHash));
  return "- " + parts.join(FIELD_SEPARATOR);
}
function validateFields(fields) {
  const problems = [];
  if (!Number.isInteger(fields.seq) || fields.seq < 1) {
    problems.push("seq must be an integer \u2265 1");
  }
  if (!TIMESTAMP_RE.test(fields.timestamp)) {
    problems.push("timestamp must be YYYY-MM-DDTHH:MM:SSZ (UTC)");
  }
  if (!ACTOR_RE.test(fields.actor) || fields.actor.endsWith(" ")) {
    problems.push(
      "actor must be non-empty, must not contain | \\ or line breaks, and must not start with # or start/end with a space"
    );
  }
  if (fields.tag !== null && !TAG_RE.test(fields.tag)) {
    problems.push("tag must match #[a-z0-9][a-z0-9_-]*");
  }
  if (fields.text.length === 0) {
    problems.push("text must be non-empty");
  }
  return problems;
}
function parseEntryLine(raw, line = 0) {
  if (!raw.startsWith("- ")) return null;
  const fieldsRaw = raw.slice(2).split(FIELD_SEPARATOR);
  if (fieldsRaw.length !== 5 && fieldsRaw.length !== 6) return null;
  const hasTag = fieldsRaw.length === 6;
  const [seqRaw, timestamp, actor] = fieldsRaw;
  const tag = hasTag ? fieldsRaw[3] : null;
  const escapedText = fieldsRaw[hasTag ? 4 : 3];
  const anchorRaw = fieldsRaw[hasTag ? 5 : 4];
  if (!SEQ_RE.test(seqRaw)) return null;
  if (!TIMESTAMP_RE.test(timestamp)) return null;
  if (!ACTOR_RE.test(actor) || actor.endsWith(" ")) return null;
  if (tag !== null && !TAG_RE.test(tag)) return null;
  if (!TEXT_RE.test(escapedText)) return null;
  if (!ANCHOR_RE.test(anchorRaw)) return null;
  const text = unescapeText(escapedText);
  if (text === null) return null;
  return {
    seq: parseInt(seqRaw, 10),
    timestamp,
    actor,
    tag,
    text,
    escapedText,
    anchor: anchorRaw.slice(1),
    line
  };
}
function parseFrontmatterValue(raw) {
  const trimmed = raw.trim();
  if (trimmed === "true") return true;
  if (trimmed === "false") return false;
  if (trimmed.startsWith('"')) {
    if (!trimmed.endsWith('"') || trimmed.length < 2) return null;
    const inner = trimmed.slice(1, -1);
    let out = "";
    for (let i = 0; i < inner.length; i++) {
      const ch = inner[i];
      if (ch === '"') return null;
      if (ch === "\\") {
        const next = inner[i + 1];
        if (next !== "\\" && next !== '"') return null;
        out += next;
        i++;
      } else {
        out += ch;
      }
    }
    return out;
  }
  return trimmed;
}
function formatFrontmatterValue(value) {
  if (typeof value === "boolean") return value ? "true" : "false";
  if (/^[A-Za-z0-9 ._-]+$/.test(value) && value === value.trim() && value !== "true" && value !== "false") {
    return value;
  }
  return '"' + value.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
}
function parseTrace(text) {
  const lines = text.split("\n").map((l) => l.replace(/\r$/, ""));
  const issues = [];
  const conventionIssues = [];
  const entries = [];
  let frontmatter = null;
  let bodyStart = 0;
  if (lines[0] === "---") {
    const end = lines.indexOf("---", 1);
    if (end === -1) {
      issues.push({
        code: "BAD_FRONTMATTER",
        line: 1,
        message: "Frontmatter is not closed with ---"
      });
      return {
        frontmatter: null,
        entries,
        issues,
        conventionIssues,
        ok: false
      };
    }
    frontmatter = {};
    for (let i = 1; i < end; i++) {
      const line = lines[i];
      if (line.trim() === "") continue;
      const colon = line.indexOf(":");
      if (colon === -1) {
        issues.push({
          code: "BAD_FRONTMATTER",
          line: i + 1,
          message: `Frontmatter line is not "key: value"`
        });
        continue;
      }
      const key = line.slice(0, colon).trim();
      const value = parseFrontmatterValue(line.slice(colon + 1));
      if (key === "" || value === null) {
        issues.push({
          code: "BAD_FRONTMATTER",
          line: i + 1,
          message: "Frontmatter value could not be parsed"
        });
        continue;
      }
      frontmatter[key] = value;
    }
    bodyStart = end + 1;
    for (const key of REQUIRED_FRONTMATTER_KEYS) {
      if (!(key in frontmatter)) {
        issues.push({
          code: "BAD_FRONTMATTER",
          line: 1,
          message: `Missing required frontmatter key "${key}"`
        });
      }
    }
  } else {
    issues.push({
      code: "MISSING_FRONTMATTER",
      line: 1,
      message: "File does not begin with --- frontmatter"
    });
  }
  for (let i = bodyStart; i < lines.length; i++) {
    const raw = lines[i];
    if (raw.trim() === "") continue;
    const entry = parseEntryLine(raw, i + 1);
    if (entry === null) {
      issues.push({
        code: "BAD_LINE",
        line: i + 1,
        message: "Line is neither blank nor a valid entry"
      });
      continue;
    }
    entries.push(entry);
    if (entry.tag === "#attest") {
      const attestation = parseAttestationPayload(entry.text);
      if (!attestation.ok) {
        conventionIssues.push({
          code: "unparseable-attestation",
          line: entry.line,
          seq: entry.seq,
          message: attestation.message
        });
      }
    } else if (entry.tag === "#rotate") {
      const rotation = parseRotationPayload(entry.text);
      if (!rotation.ok) {
        conventionIssues.push({
          code: "unparseable-rotation",
          line: entry.line,
          seq: entry.seq,
          message: rotation.message
        });
      }
    }
  }
  return {
    frontmatter,
    entries,
    issues,
    conventionIssues,
    ok: issues.length === 0
  };
}
async function verifyTrace(text) {
  const parsed = parseTrace(text);
  const issues = [...parsed.issues];
  const conventionIssues = [...parsed.conventionIssues];
  const entries = [];
  const format = parsed.frontmatter?.["format"];
  if (parsed.frontmatter !== null && format !== FORMAT_TOKEN) {
    issues.push({
      code: "UNKNOWN_FORMAT",
      line: 1,
      message: `Unknown format "${String(format)}" (expected ${FORMAT_TOKEN}); chain not verified`
    });
    return {
      ok: false,
      entryCount: parsed.entries.length,
      headHash: null,
      entries: parsed.entries.map((e) => ({ ...e, fullHash: null })),
      issues,
      conventionIssues
    };
  }
  if (parsed.entries.length === 0) {
    issues.push({
      code: "MISSING_GENESIS",
      line: 0,
      message: "Trace has no entries (genesis entry with seq 1 required)"
    });
  }
  let prevSeq = 0;
  let prevHash = GENESIS;
  let chainBroken = false;
  for (const entry of parsed.entries) {
    if (entry.seq !== prevSeq + 1) {
      if (prevSeq === 0) {
        issues.push({
          code: "MISSING_GENESIS",
          line: entry.line,
          seq: entry.seq,
          message: `First entry has seq ${entry.seq}; genesis must be seq 1`
        });
      } else if (entry.seq <= prevSeq) {
        issues.push({
          code: "SEQ_DUPLICATE",
          line: entry.line,
          seq: entry.seq,
          message: `Sequence went from ${prevSeq} to ${entry.seq}; entries inserted, duplicated, or reordered`
        });
      } else {
        issues.push({
          code: "SEQ_GAP",
          line: entry.line,
          seq: entry.seq,
          message: `Sequence jumped from ${prevSeq} to ${entry.seq}; ${entry.seq - prevSeq - 1} entr${entry.seq - prevSeq - 1 === 1 ? "y" : "ies"} missing`
        });
      }
    }
    prevSeq = entry.seq;
    if (Number.isNaN(Date.parse(entry.timestamp))) {
      issues.push({
        code: "BAD_TIMESTAMP",
        line: entry.line,
        seq: entry.seq,
        message: `Timestamp "${entry.timestamp}" is not a real date-time`
      });
    }
    let fullHash = null;
    if (!chainBroken && prevHash !== null) {
      const computed = await computeEntryHash(prevHash, entry);
      if (toAnchor(computed) === entry.anchor) {
        fullHash = computed;
        prevHash = computed;
      } else {
        issues.push({
          code: "HASH_MISMATCH",
          line: entry.line,
          seq: entry.seq,
          message: `Anchor #${entry.anchor} does not match recomputed #${toAnchor(computed)}; content at or before seq ${entry.seq} changed after it was written`
        });
        chainBroken = true;
        prevHash = null;
      }
    }
    entries.push({ ...entry, fullHash });
  }
  const ok = issues.length === 0;
  return {
    ok,
    entryCount: parsed.entries.length,
    headHash: ok && entries.length > 0 ? entries[entries.length - 1].fullHash : null,
    entries,
    issues,
    conventionIssues
  };
}

// src/format.ts
function nowTimestamp(now = /* @__PURE__ */ new Date()) {
  return now.toISOString().replace(/\.\d{3}Z$/, "Z");
}
function traceFileName(traceSlug, actorSlug) {
  return `${traceSlug}.${actorSlug}.md`;
}
function currentSegmentMonth(now = /* @__PURE__ */ new Date()) {
  return now.toISOString().slice(0, 7);
}
function traceSegmentFileName(segment, startMonth, actorSlug) {
  return `${String(segment).padStart(4, "0")}-${startMonth}.${actorSlug}.md`;
}
function traceSegmentPath(tracesFolder, traceSlug, segment, startMonth, actorSlug) {
  const folder = tracesFolder ? tracesFolder + "/" : "";
  return folder + traceSlug + "/" + traceSegmentFileName(segment, startMonth, actorSlug);
}
function parseTraceFileName(name) {
  const parts = name.split(".");
  if (parts.length !== 3 || parts[2] !== "md") return null;
  const [traceSlug, actorSlug] = parts;
  if (!isValidSlug(traceSlug) || !isValidSlug(actorSlug)) return null;
  return { traceSlug, actorSlug };
}
function parseTracePath(path, tracesFolder) {
  const prefix = tracesFolder ? tracesFolder.replace(/^\/+|\/+$/g, "") + "/" : "";
  if (prefix && !path.startsWith(prefix)) return null;
  const rest = prefix ? path.slice(prefix.length) : path;
  const parts = rest.split("/");
  if (parts.length === 1) {
    const legacy = parseTraceFileName(parts[0]);
    return legacy ? { ...legacy, segment: null, startMonth: null, legacy: true } : null;
  }
  if (parts.length !== 2) return null;
  const [traceSlug, name] = parts;
  if (!isValidSlug(traceSlug)) return null;
  const match = /^(\d{4})-(\d{4}-\d{2})\.([a-z0-9]+(?:-[a-z0-9]+)*)\.md$/.exec(name);
  if (!match) return null;
  const segment = parseInt(match[1], 10);
  const startMonth = match[2];
  const actorSlug = match[3];
  if (segment < 1 || !isValidSlug(actorSlug)) return null;
  return { traceSlug, actorSlug, segment, startMonth, legacy: false };
}
function tracePathOrder(path, tracesFolder) {
  const info = parseTracePath(path, tracesFolder);
  return info?.segment ?? 0;
}
function buildFrontmatter(meta) {
  const pairs = [
    ["trace", true],
    ["format", FORMAT_TOKEN],
    ["trace_name", meta.traceName],
    ["trace_slug", meta.traceSlug],
    ["actor_name", meta.actorName],
    ["actor_slug", meta.actorSlug],
    ["actor_id", meta.actorId]
  ];
  const lines = pairs.map(([k, v]) => `${k}: ${formatFrontmatterValue(v)}`);
  return "---\n" + lines.join("\n") + "\n---\n";
}
function metaFromFrontmatter(fm) {
  if (!fm) return null;
  const traceName = fm["trace_name"];
  const traceSlug = fm["trace_slug"];
  const actorName = fm["actor_name"];
  const actorSlug = fm["actor_slug"];
  const actorId = fm["actor_id"];
  if (fm["trace"] !== true || typeof traceName !== "string" || typeof traceSlug !== "string" || typeof actorName !== "string" || typeof actorSlug !== "string" || typeof actorId !== "string") {
    return null;
  }
  return { traceName, traceSlug, actorName, actorSlug, actorId };
}
function genesisFields(meta, timestamp) {
  return {
    seq: 1,
    timestamp,
    actor: meta.actorName,
    tag: "#genesis",
    text: `Trace "${meta.traceName}" started by ${meta.actorName}`
  };
}
function validateName(name) {
  if (name.trim() !== name || name.length === 0) {
    return "Name must not be empty or start/end with a space";
  }
  if (/[|\\\r\n]/.test(name)) {
    return "Name must not contain |, \\, or line breaks";
  }
  if (name.startsWith("#")) {
    return "Name must not start with #";
  }
  if (!isValidSlug(slugify(name))) {
    return "Name must contain at least one letter or digit";
  }
  return null;
}
var TEMPLATE_PLACEHOLDERS = [
  "{{seq}}",
  "{{timestamp}}",
  "{{actor}}",
  "{{tag}}",
  "{{text}}",
  "{{hash}}"
];
var DEFAULT_TEMPLATE = "{{seq}} | {{timestamp}} | {{actor}} | {{tag}} | {{text}} | {{hash}}";
function validateTemplate(template) {
  let rest = template;
  for (const ph of TEMPLATE_PLACEHOLDERS) {
    const first = rest.indexOf(ph);
    if (first === -1) {
      const inFull = template.indexOf(ph) !== -1;
      return inFull ? `Placeholders must appear in canonical order (${ph} is out of order)` : `Template must contain ${ph}`;
    }
    rest = rest.slice(first + ph.length);
  }
  for (const ph of TEMPLATE_PLACEHOLDERS) {
    const first = template.indexOf(ph);
    if (template.indexOf(ph, first + ph.length) !== -1) {
      return `Template must contain ${ph} exactly once`;
    }
  }
  const leftover = template.replace(/\{\{(seq|timestamp|actor|tag|text|hash)\}\}/g, "").match(/\{\{[^}]*\}\}/);
  if (leftover) {
    return `Unknown placeholder ${leftover[0]}`;
  }
  return null;
}
function renderTemplateSegments(template, entry) {
  const values = {
    seq: String(entry.seq),
    timestamp: entry.timestamp,
    actor: entry.actor,
    tag: entry.tag ?? "",
    text: entry.text,
    hash: "#" + entry.anchor
  };
  const segments = [];
  const re = /\{\{(seq|timestamp|actor|tag|text|hash)\}\}/g;
  let last = 0;
  let m;
  while ((m = re.exec(template)) !== null) {
    if (m.index > last) {
      segments.push({ kind: "literal", value: template.slice(last, m.index) });
    }
    const kind = m[1];
    segments.push({ kind, value: values[m[1]] });
    last = m.index + m[0].length;
  }
  if (last < template.length) {
    segments.push({ kind: "literal", value: template.slice(last) });
  }
  return segments;
}

// src/appendModal.ts
var AppendEntryModal = class extends import_obsidian.Modal {
  constructor(plugin, initialTraceSlug) {
    super(plugin.app);
    this.plugin = plugin;
    this.traceSlug = "";
    this.tag = null;
    this.text = "";
    if (initialTraceSlug) this.traceSlug = initialTraceSlug;
  }
  onOpen() {
    this.setTitle("Append entry");
    const traces = this.plugin.registry.logicalTraces();
    if (traces.length === 0) {
      this.contentEl.createEl("p", {
        text: "No traces exist yet. Create one first."
      });
      new import_obsidian.Setting(this.contentEl).addButton(
        (btn) => btn.setButtonText("Create timeline").setCta().onClick(() => {
          this.close();
          new CreateTraceModal(this.plugin).open();
        })
      );
      return;
    }
    if (!this.traceSlug || !traces.some((t) => t.slug === this.traceSlug)) {
      this.traceSlug = this.plugin.lastUsedTrace ?? traces[0].slug;
      if (!traces.some((t) => t.slug === this.traceSlug)) {
        this.traceSlug = traces[0].slug;
      }
    }
    new import_obsidian.Setting(this.contentEl).setName("Trace").addDropdown((dropdown) => {
      for (const trace of traces) {
        dropdown.addOption(trace.slug, trace.name);
      }
      dropdown.setValue(this.traceSlug).onChange((value) => {
        this.traceSlug = value;
      });
    });
    new import_obsidian.Setting(this.contentEl).setName("Tag").addDropdown((dropdown) => {
      dropdown.addOption("", "None");
      for (const tag of this.plugin.settings.tagSet) {
        dropdown.addOption(tag, "#" + tag);
      }
      dropdown.setValue(this.tag ?? "").onChange((value) => {
        this.tag = value === "" ? null : value;
      });
    });
    const textSetting = new import_obsidian.Setting(this.contentEl).setName("Text").setClass("trace-append-text");
    textSetting.addTextArea((textArea) => {
      textArea.setPlaceholder("What happened?").onChange((value) => {
        this.text = value;
      });
      textArea.inputEl.rows = 4;
      textArea.inputEl.addEventListener("keydown", (event) => {
        if ((event.metaKey || event.ctrlKey) && event.key === "Enter") {
          event.preventDefault();
          void this.submit();
        }
      });
      window.setTimeout(() => textArea.inputEl.focus(), 0);
    });
    new import_obsidian.Setting(this.contentEl).addButton(
      (btn) => btn.setButtonText("Append").setCta().onClick(() => void this.submit())
    );
  }
  async submit() {
    const text = this.text.trim();
    if (text.length === 0) {
      new import_obsidian.Notice("Entry text can't be empty.");
      return;
    }
    const trace = this.plugin.registry.logicalTraces().find((t) => t.slug === this.traceSlug);
    if (!trace) {
      new import_obsidian.Notice("Pick a trace first.");
      return;
    }
    this.close();
    await this.plugin.appendToTrace(
      trace.slug,
      trace.name,
      this.tag ? "#" + this.tag : null,
      text
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};
var RecordFileChangeModal = class extends import_obsidian.Modal {
  constructor(plugin, file) {
    super(plugin.app);
    this.plugin = plugin;
    this.file = file;
    this.traceSlug = "";
    this.change = "modify";
  }
  onOpen() {
    this.setTitle("Record file change");
    const traces = this.plugin.registry.logicalTraces();
    if (traces.length === 0) {
      this.contentEl.createEl("p", {
        text: "No traces exist yet. Create one before recording a file change."
      });
      return;
    }
    this.traceSlug = this.plugin.lastUsedTrace ?? traces[0].slug;
    if (!traces.some((trace) => trace.slug === this.traceSlug)) {
      this.traceSlug = traces[0].slug;
    }
    this.contentEl.createEl("p", {
      text: `This writes a #attest entry for ${this.file.path}.`
    });
    new import_obsidian.Setting(this.contentEl).setName("Trace").addDropdown((dropdown) => {
      for (const trace of traces) {
        dropdown.addOption(trace.slug, trace.name);
      }
      dropdown.setValue(this.traceSlug).onChange((value) => {
        this.traceSlug = value;
      });
    });
    new import_obsidian.Setting(this.contentEl).setName("Change").addDropdown((dropdown) => {
      dropdown.addOption("modify", "Modify").addOption("create", "Create").setValue(this.change).onChange((value) => {
        this.change = value === "create" ? "create" : "modify";
      });
    });
    new import_obsidian.Setting(this.contentEl).addButton(
      (btn) => btn.setButtonText("Record").setCta().onClick(() => void this.submit())
    );
  }
  async submit() {
    const trace = this.plugin.registry.logicalTraces().find((t) => t.slug === this.traceSlug);
    if (!trace) {
      new import_obsidian.Notice("Pick a trace first.");
      return;
    }
    try {
      const bytes = await this.plugin.app.vault.readBinary(this.file);
      const sha256 = await sha256Bytes(bytes);
      const payload = formatAttestationPayload({
        change: this.change,
        path: this.file.path,
        sha256
      });
      this.close();
      await this.plugin.appendToTrace(trace.slug, trace.name, "#attest", payload);
    } catch (error) {
      new import_obsidian.Notice(
        `Attestation failed: ${error instanceof Error ? error.message : String(error)}`
      );
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var CreateTraceModal = class extends import_obsidian.Modal {
  constructor(plugin) {
    super(plugin.app);
    this.plugin = plugin;
    this.name = "";
  }
  onOpen() {
    this.setTitle("Create timeline");
    this.contentEl.createEl("p", {
      text: "A trace is a shared timeline. Each device appends to its own file inside it."
    });
    new import_obsidian.Setting(this.contentEl).setName("Trace name").addText((text) => {
      text.setPlaceholder("E.g. Project log").onChange((value) => {
        this.name = value;
      });
      text.inputEl.addEventListener("keydown", (event) => {
        if (event.key === "Enter") {
          event.preventDefault();
          void this.submit();
        }
      });
      window.setTimeout(() => text.inputEl.focus(), 0);
    });
    new import_obsidian.Setting(this.contentEl).addButton(
      (btn) => btn.setButtonText("Create").setCta().onClick(() => void this.submit())
    );
  }
  async submit() {
    const name = this.name.trim();
    const invalid = validateName(name);
    if (invalid) {
      new import_obsidian.Notice(invalid);
      return;
    }
    const slug = slugify(name);
    const existing = this.plugin.registry.logicalTraces().find((t) => t.slug === slug);
    if (existing && existing.name !== name) {
      new import_obsidian.Notice(
        `"${name}" collides with existing trace "${existing.name}" (both become "${slug}"). Pick a different name.`
      );
      return;
    }
    this.close();
    await this.plugin.createTrace(name, slug);
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/guard.ts
var import_obsidian2 = require("obsidian");
var import_obsidian3 = require("obsidian");
var import_state = require("@codemirror/state");
function classifyChange(oldContent, newContent) {
  if (newContent === oldContent) return { kind: "unchanged" };
  if (newContent.startsWith(oldContent)) {
    return { kind: "append", tail: newContent.slice(oldContent.length) };
  }
  return { kind: "rewrite" };
}
async function validateAppendedTail(tail, prevSeq, prevHead, expectedActor) {
  const lines = tail.split("\n");
  let seq = prevSeq;
  let head = prevHead;
  const entries = [];
  for (const line of lines) {
    if (line.trim() === "") continue;
    const entry = parseEntryLine(line);
    if (entry === null) {
      return { ok: false, reason: "appended line is not a valid entry" };
    }
    if (entry.seq !== seq + 1) {
      return {
        ok: false,
        reason: `appended entry has seq ${entry.seq}, expected ${seq + 1}`
      };
    }
    if (entry.actor !== expectedActor) {
      return {
        ok: false,
        reason: `appended entry actor "${entry.actor}" does not match this file's writer "${expectedActor}"`
      };
    }
    const computed = await computeEntryHash(head, entry);
    if (toAnchor(computed) !== entry.anchor) {
      return {
        ok: false,
        reason: `appended entry #${entry.anchor} does not continue the chain`
      };
    }
    seq = entry.seq;
    head = computed;
    entries.push(entry);
  }
  if (entries.length === 0) {
    return { ok: false, reason: "no entries in appended content" };
  }
  return { ok: true, seq, head, entries };
}
function protectedEndOffset(doc) {
  const lines = doc.split("\n");
  let offset = 0;
  let protectedEnd = 0;
  let inFrontmatter = false;
  let frontmatterClosed = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const lineEnd = offset + line.length;
    const withNewline = Math.min(lineEnd + 1, doc.length);
    if (i === 0 && line === "---") {
      inFrontmatter = true;
      protectedEnd = withNewline;
    } else if (inFrontmatter && !frontmatterClosed) {
      protectedEnd = withNewline;
      if (line === "---") frontmatterClosed = true;
    } else if (parseEntryLine(line) !== null) {
      protectedEnd = withNewline;
    }
    offset = lineEnd + 1;
  }
  return protectedEnd;
}
var SELF_WRITE_WINDOW_MS = 3e3;
var DEBOUNCE_MS = 350;
var STARTUP_GRACE_MS = 45e3;
var REVERT_WINDOW_MS = 12e4;
var MAX_REVERTS_PER_WINDOW = 2;
var NOTICE_THROTTLE_MS = 5e3;
var TraceGuard = class {
  constructor(host) {
    this.host = host;
    this.cache = /* @__PURE__ */ new Map();
    this.selfWrites = /* @__PURE__ */ new Map();
    this.timers = /* @__PURE__ */ new Map();
    this.reverts = /* @__PURE__ */ new Map();
    this.lastNotice = /* @__PURE__ */ new Map();
    this.readyAt = Date.now();
    /** Files flagged since last verify; surfaced by the verify command. */
    this.suspect = /* @__PURE__ */ new Set();
  }
  setWriter(writer) {
    this.host.writer = writer;
  }
  writer() {
    if (!this.host.writer) {
      throw new Error("Trace writer is not initialized");
    }
    return this.host.writer;
  }
  markSelfWrite(path) {
    this.selfWrites.set(path, Date.now());
  }
  isSelfWrite(path) {
    const at = this.selfWrites.get(path);
    return at !== void 0 && Date.now() - at < SELF_WRITE_WINDOW_MS;
  }
  setCache(path, content) {
    this.cache.set(path, { content, confirmed: true });
  }
  getCachedContent(path) {
    const entry = this.cache.get(path);
    return entry?.confirmed ? entry.content : null;
  }
  dropPath(path) {
    this.cache.delete(path);
    this.suspect.delete(path);
    const timer = this.timers.get(path);
    if (timer !== void 0) {
      window.clearTimeout(timer);
      this.timers.delete(path);
    }
  }
  renamePath(oldPath, newPath) {
    const entry = this.cache.get(oldPath);
    this.cache.delete(oldPath);
    if (entry) this.cache.set(newPath, entry);
    if (this.suspect.delete(oldPath)) this.suspect.add(newPath);
  }
  dispose() {
    for (const timer of this.timers.values()) {
      window.clearTimeout(timer);
    }
    this.timers.clear();
  }
  /** Read all known trace files once at layout-ready so later modify
   * events have a trusted baseline; resets the startup grace window. */
  async warmCache(paths) {
    this.readyAt = Date.now();
    for (const path of paths) {
      const file = this.host.app.vault.getAbstractFileByPath(path);
      if (!(file instanceof import_obsidian2.TFile)) continue;
      try {
        const content = await this.host.app.vault.cachedRead(file);
        this.cache.set(path, { content, confirmed: true });
        const state = this.host.chain.get(path);
        if (state && state.contentSha !== await sha256Hex(content)) {
          await this.reconcile(path, content);
        }
      } catch {
      }
    }
  }
  /** File content differs from the recorded chain state: verify, adopt
   * silently when the file is simply ahead and intact, warn otherwise. */
  async reconcile(path, content) {
    const meta = this.host.getMeta(path);
    if (!meta) return;
    const state = this.host.chain.get(path);
    const result = await verifyTrace(content);
    if (result.ok && result.headHash !== null) {
      const lastSeq = result.entries[result.entries.length - 1].seq;
      if (!state || lastSeq > state.seq) {
        await this.host.chain.set(path, {
          seq: lastSeq,
          head: result.headHash,
          entryCount: result.entryCount,
          contentSha: await sha256Hex(content),
          updatedAt: (/* @__PURE__ */ new Date()).toISOString()
        });
        return;
      }
      if (lastSeq === state.seq && result.headHash === state.head) {
        await this.host.chain.set(path, {
          ...state,
          contentSha: await sha256Hex(content)
        });
        return;
      }
    }
    this.suspect.add(path);
    this.notice(
      `Trace "${meta.traceName}" (${meta.actorName}): content changed outside the append path (edit, sync merge, or external tool). Run "Verify integrity".`,
      path
    );
  }
  onModify(file) {
    const path = file.path;
    if (!this.host.getMeta(path)) return;
    if (this.isSelfWrite(path)) return;
    const existing = this.timers.get(path);
    if (existing !== void 0) window.clearTimeout(existing);
    this.timers.set(
      path,
      window.setTimeout(() => {
        this.timers.delete(path);
        void this.evaluate(path);
      }, DEBOUNCE_MS)
    );
  }
  async evaluate(path) {
    const meta = this.host.getMeta(path);
    if (!meta) return;
    if (this.isSelfWrite(path)) return;
    const file = this.host.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian2.TFile)) return;
    let newContent;
    try {
      newContent = await this.host.app.vault.read(file);
    } catch {
      return;
    }
    const cached = this.cache.get(path);
    if (!cached || !cached.confirmed) {
      this.cache.set(path, { content: newContent, confirmed: true });
      await this.reconcile(path, newContent);
      return;
    }
    const change = classifyChange(cached.content, newContent);
    if (change.kind === "unchanged") return;
    if (change.kind === "append") {
      const state = this.host.chain.get(path);
      const cachedSha = await sha256Hex(cached.content);
      if (state && state.contentSha === cachedSha) {
        const tailCheck = await validateAppendedTail(
          change.tail,
          state.seq,
          state.head,
          meta.actorName
        );
        if (tailCheck.ok && tailCheck.head && tailCheck.seq && tailCheck.entries) {
          this.cache.set(path, { content: newContent, confirmed: true });
          await this.host.chain.set(path, {
            seq: tailCheck.seq,
            head: tailCheck.head,
            entryCount: state.entryCount + tailCheck.entries.length,
            contentSha: await sha256Hex(newContent),
            updatedAt: (/* @__PURE__ */ new Date()).toISOString()
          });
          return;
        }
      } else {
        const result = await verifyTrace(newContent);
        if (result.ok && result.headHash !== null) {
          const lastSeq = result.entries[result.entries.length - 1].seq;
          if (!state || lastSeq >= state.seq) {
            this.cache.set(path, {
              content: newContent,
              confirmed: true
            });
            await this.host.chain.set(path, {
              seq: lastSeq,
              head: result.headHash,
              entryCount: result.entryCount,
              contentSha: await sha256Hex(newContent),
              updatedAt: (/* @__PURE__ */ new Date()).toISOString()
            });
            return;
          }
        }
      }
    }
    await this.violation(file, meta, cached.content, newContent);
  }
  async violation(file, meta, oldContent, newContent) {
    const path = file.path;
    const identity = this.host.getIdentity();
    const own = identity !== null && meta.actorId === identity.actorId;
    const label = `Trace "${meta.traceName}" (${meta.actorName})`;
    if (!own) {
      this.suspect.add(path);
      this.cache.set(path, { content: newContent, confirmed: true });
      this.notice(
        `${label}: content changed outside the append path (edit, sync merge, or external tool). Run "Verify integrity".`,
        path
      );
      return;
    }
    const mode = this.host.getSettings().enforcementMode;
    const inGrace = Date.now() - this.readyAt < STARTUP_GRACE_MS;
    if (mode === "enforce" && !inGrace && this.mayRevert(path)) {
      this.recordRevert(path);
      await this.writer().replaceContent(file, oldContent, null);
      this.cache.set(path, { content: oldContent, confirmed: true });
      this.notice(
        `${label}: content changed outside the append path \u2014 reverted to the last verified state.`,
        path
      );
      return;
    }
    this.suspect.add(path);
    this.cache.set(path, { content: newContent, confirmed: true });
    const suffix = mode === "enforce" ? "Not auto-reverted (recent start or repeated changes \u2014 possibly sync). " : "";
    this.notice(
      `${label}: content changed outside the append path (edit, sync merge, or external tool). ${suffix}Run "Verify integrity".`,
      path
    );
  }
  mayRevert(path) {
    const now = Date.now();
    const recent = (this.reverts.get(path) ?? []).filter(
      (t) => now - t < REVERT_WINDOW_MS
    );
    this.reverts.set(path, recent);
    return recent.length < MAX_REVERTS_PER_WINDOW;
  }
  recordRevert(path) {
    const list = this.reverts.get(path) ?? [];
    list.push(Date.now());
    this.reverts.set(path, list);
  }
  onRename(file, oldPath) {
    if (this.isSelfWrite(oldPath) || this.isSelfWrite(file.path)) return;
    const wasTrace = this.cache.has(oldPath) || this.host.chain.get(oldPath);
    this.renamePath(oldPath, file.path);
    void this.host.chain.rename(oldPath, file.path);
    if (wasTrace || this.host.getMeta(file.path)) {
      this.notice(
        `Trace file "${oldPath}" was renamed to "${file.path}". External tools referencing the old path will not find it; the file name should stay <trace>.<actor>.md.`,
        oldPath
      );
    }
  }
  onDelete(path) {
    if (!this.cache.has(path) && !this.host.chain.get(path)) return;
    this.dropPath(path);
    this.notice(
      `Trace file "${path}" was deleted. Its recorded chain state is kept as evidence; run "Verify all" to review or forget it.`,
      path
    );
  }
  notice(message, key = "") {
    const now = Date.now();
    const last = this.lastNotice.get(key + message) ?? 0;
    if (now - last < NOTICE_THROTTLE_MS) return;
    this.lastNotice.set(key + message, now);
    new import_obsidian2.Notice(message, 8e3);
  }
};
function buildEditorGuard(host, guard) {
  const protectedEnds = /* @__PURE__ */ new WeakMap();
  return import_state.EditorState.transactionFilter.of((tr) => {
    if (!tr.docChanged) return tr;
    if (!host.getSettings().readOnlyGuard) return tr;
    const info = tr.startState.field(import_obsidian3.editorInfoField, false);
    const file = info?.file;
    if (!file) return tr;
    const meta = host.getMeta(file.path);
    if (!meta) return tr;
    const identity = host.getIdentity();
    const own = identity !== null && meta.actorId === identity.actorId;
    if (!own) {
      guard.notice(
        `Read-only: this trace file belongs to "${meta.actorName}". Entries are appended from that device.`,
        file.path
      );
      return [];
    }
    const doc = tr.startState.doc;
    let boundary = protectedEnds.get(doc);
    if (boundary === void 0) {
      boundary = protectedEndOffset(doc.toString());
      protectedEnds.set(doc, boundary);
    }
    let blocked = false;
    tr.changes.iterChangedRanges((fromA) => {
      if (fromA < boundary) blocked = true;
    });
    if (blocked) {
      guard.notice(
        "Trace entries are append-only \u2014 existing entries can't be edited. Use the append command instead.",
        file.path
      );
      return [];
    }
    return tr;
  });
}

// src/hashchain.ts
var import_obsidian4 = require("obsidian");
var ChainStore = class {
  constructor(persist) {
    this.persist = persist;
    this.states = {};
  }
  loadFrom(states) {
    this.states = states ?? {};
  }
  snapshot() {
    return this.states;
  }
  get(path) {
    return this.states[path] ?? null;
  }
  async set(path, state) {
    this.states[path] = state;
    await this.persist();
  }
  async remove(path) {
    if (path in this.states) {
      delete this.states[path];
      await this.persist();
    }
  }
  async rename(oldPath, newPath) {
    const state = this.states[oldPath];
    if (state) {
      delete this.states[oldPath];
      this.states[newPath] = state;
      await this.persist();
    }
  }
  paths() {
    return Object.keys(this.states);
  }
};
var AppendBlockedError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "AppendBlockedError";
  }
};
var TraceWriter = class {
  constructor(deps) {
    this.deps = deps;
    this.queues = /* @__PURE__ */ new Map();
  }
  get vault() {
    return this.deps.app.vault;
  }
  /** Run `fn` exclusively for `path`; appends to one file never race. */
  enqueue(path, fn) {
    const prev = this.queues.get(path) ?? Promise.resolve();
    const next = prev.then(fn, fn);
    this.queues.set(
      path,
      next.catch(() => void 0)
    );
    return next;
  }
  async ensureFolder(folderPath) {
    const normalized = folderPath.replace(/^\/+|\/+$/g, "");
    if (normalized === "") return;
    const parts = normalized.split("/");
    let current = "";
    for (const part of parts) {
      current = current ? current + "/" + part : part;
      const existing = this.vault.getAbstractFileByPath(current);
      if (existing instanceof import_obsidian4.TFolder) continue;
      if (existing !== null) {
        throw new AppendBlockedError(
          `"${current}" exists but is not a folder`
        );
      }
      await this.vault.createFolder(current);
    }
  }
  /**
   * Create a new writer file for a logical trace: frontmatter plus the
   * genesis entry (seq 1). Fails if the file already exists.
   */
  async createTraceFile(folderPath, meta, options = {}) {
    const path = options.path ?? (folderPath ? folderPath + "/" : "") + traceFileName(meta.traceSlug, meta.actorSlug);
    return this.enqueue(path, async () => {
      if (this.vault.getAbstractFileByPath(path) !== null) {
        throw new AppendBlockedError(`"${path}" already exists`);
      }
      await this.ensureFolder(path.split("/").slice(0, -1).join("/"));
      const fields = options.initialFields ?? genesisFields(meta, nowTimestamp());
      const fullHash = await computeEntryHash(
        "0".repeat(64),
        fields
      );
      const content = buildFrontmatter(meta) + formatEntryLine(fields, fullHash) + "\n";
      this.deps.markSelfWrite(path);
      const file = await this.vault.create(path, content);
      this.deps.setCache(path, content);
      await this.deps.chain.set(path, {
        seq: 1,
        head: fullHash,
        entryCount: 1,
        contentSha: await sha256Hex(content),
        updatedAt: nowTimestamp()
      });
      return file;
    });
  }
  /**
   * Append one entry to a writer file. Establishes the trusted head first:
   * fast path when the file's content hash matches the stored state; slow
   * path re-verifies the whole file and adopts it when the chain is intact
   * and not behind the stored state. Anything else blocks the append —
   * appending onto a suspect chain would fork every anchor after it.
   */
  async appendEntry(file, meta, input) {
    return this.enqueue(file.path, async () => {
      const content = await this.vault.read(file);
      const contentSha = await sha256Hex(content);
      const state = this.deps.chain.get(file.path);
      let prevSeq;
      let prevHead;
      if (state && state.contentSha === contentSha) {
        prevSeq = state.seq;
        prevHead = state.head;
      } else {
        const result = await verifyTrace(content);
        if (!result.ok || result.headHash === null) {
          throw new AppendBlockedError(
            `"${file.path}" failed verification \u2014 content changed outside the append path (edit, sync merge, or external tool). Run "Verify integrity".`
          );
        }
        const lastSeq = result.entries[result.entries.length - 1].seq;
        if (state && lastSeq < state.seq) {
          throw new AppendBlockedError(
            `"${file.path}" has ${lastSeq} entries but seq ${state.seq} was previously recorded \u2014 entries were removed from the end, or sync has not caught up. Run "Verify integrity".`
          );
        }
        if (state && lastSeq === state.seq && result.headHash !== state.head) {
          throw new AppendBlockedError(
            `"${file.path}" diverged from its last recorded head \u2014 content changed outside the append path. Run "Verify integrity".`
          );
        }
        prevSeq = lastSeq;
        prevHead = result.headHash;
      }
      const fields = {
        seq: prevSeq + 1,
        timestamp: nowTimestamp(),
        actor: meta.actorName,
        tag: input.tag,
        text: input.text
      };
      const problems = validateFields(fields);
      if (problems.length > 0) {
        throw new AppendBlockedError(problems.join("; "));
      }
      const fullHash = await computeEntryHash(prevHead, fields);
      const line = formatEntryLine(fields, fullHash);
      const glue = content === "" || content.endsWith("\n") ? "" : "\n";
      this.deps.markSelfWrite(file.path);
      await this.vault.append(file, glue + line + "\n");
      const newContent = content + glue + line + "\n";
      this.deps.setCache(file.path, newContent);
      await this.deps.chain.set(file.path, {
        seq: fields.seq,
        head: fullHash,
        entryCount: fields.seq,
        contentSha: await sha256Hex(newContent),
        updatedAt: nowTimestamp()
      });
      return { seq: fields.seq, anchor: toAnchor(fullHash), line };
    });
  }
  /**
   * Replace a file's content through the plugin's own write path (used by
   * revert and re-baseline). Content must already be fully formed.
   */
  async replaceContent(file, newContent, newState) {
    return this.enqueue(file.path, async () => {
      this.deps.markSelfWrite(file.path);
      await this.vault.process(file, () => newContent);
      this.deps.setCache(file.path, newContent);
      if (newState) {
        await this.deps.chain.set(file.path, newState);
      }
    });
  }
};

// src/identity.ts
var import_obsidian5 = require("obsidian");
var STORAGE_KEY = "trace-identity";
function defaultActorName(actorId) {
  return `Device ${actorId.slice(0, 8)}`;
}
function isIdentity(value) {
  if (typeof value !== "object" || value === null) return false;
  const v = value;
  return typeof v.actorId === "string" && v.actorId.length > 0 && typeof v.actorName === "string" && typeof v.actorSlug === "string";
}
var IdentityManager = class {
  constructor(app) {
    this.app = app;
    this.identity = null;
  }
  /** Load identity from device-local storage. */
  load() {
    const raw = this.app.loadLocalStorage(STORAGE_KEY);
    let value = raw;
    if (typeof raw === "string") {
      try {
        value = JSON.parse(raw);
      } catch {
        value = null;
      }
    }
    this.identity = isIdentity(value) ? value : null;
    return this.identity;
  }
  get() {
    return this.identity;
  }
  save(identity) {
    this.identity = identity;
    this.app.saveLocalStorage(STORAGE_KEY, identity);
  }
  /** Create and persist a brand-new identity for this device. */
  create(actorName) {
    const identity = {
      actorId: crypto.randomUUID(),
      actorName,
      actorSlug: slugify(actorName)
    };
    this.save(identity);
    return identity;
  }
  /** Create and persist an automatic identity for first use. */
  createDefault() {
    const actorId = crypto.randomUUID();
    const actorName = defaultActorName(actorId);
    const identity = {
      actorId,
      actorName,
      actorSlug: slugify(actorName)
    };
    this.save(identity);
    return identity;
  }
  /** Adopt an existing actor (identity recovery after cleared storage). */
  reclaim(meta) {
    const identity = {
      actorId: meta.actorId,
      actorName: meta.actorName,
      actorSlug: meta.actorSlug
    };
    this.save(identity);
    return identity;
  }
};
function checkNameAgainstActors(name, others) {
  const invalid = validateName(name);
  if (invalid) return invalid;
  const slug = slugify(name);
  const clash = others.find((a) => a.actorSlug === slug);
  if (clash) {
    return `"${name}" would use the file name segment "${slug}", already taken by writer "${clash.actorName}"`;
  }
  return null;
}
var DeviceNameModal = class extends import_obsidian5.Modal {
  constructor(app, otherActors, onSubmit, initial = "") {
    super(app);
    this.otherActors = otherActors;
    this.onSubmit = onSubmit;
    this.initial = initial;
    this.value = "";
    this.registerError = () => {
    };
    this.value = initial;
  }
  onOpen() {
    this.setTitle("Name this device");
    this.contentEl.createEl("p", {
      text: "Entries written on this device are attributed to this name. It also becomes part of trace file names, so it must differ from other devices."
    });
    let errorEl = null;
    new import_obsidian5.Setting(this.contentEl).setName("Device name").addText((text) => {
      text.setValue(this.value).setPlaceholder("E.g. Laptop").onChange((v) => {
        this.value = v;
        if (errorEl) errorEl.setText("");
      });
      text.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          e.preventDefault();
          this.submit();
        }
      });
    });
    errorEl = this.contentEl.createEl("p", { cls: "trace-error" });
    new import_obsidian5.Setting(this.contentEl).addButton(
      (btn) => btn.setButtonText("Save").setCta().onClick(() => this.submit())
    );
    this.registerError = (msg) => errorEl?.setText(msg);
  }
  submit() {
    const error = checkNameAgainstActors(this.value, this.otherActors);
    if (error) {
      this.registerError(error);
      return;
    }
    this.close();
    this.onSubmit(this.value);
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ReclaimIdentityModal = class extends import_obsidian5.Modal {
  constructor(app, actors, onReclaim, onCreateNew) {
    super(app);
    this.actors = actors;
    this.onReclaim = onReclaim;
    this.onCreateNew = onCreateNew;
  }
  onOpen() {
    this.setTitle("Reconnect this device to a writer");
    this.contentEl.createEl("p", {
      text: "This device has no writer identity, but this vault contains trace files. If this device wrote some of them (for example after a reinstall), reclaim that writer so its traces stay owned. Otherwise create a new identity."
    });
    for (const actor of this.actors) {
      new import_obsidian5.Setting(this.contentEl).setName(actor.actorName).setDesc(`Writer id ${actor.actorId}`).addButton(
        (btn) => btn.setButtonText("Reclaim").onClick(() => {
          this.close();
          this.onReclaim(actor);
        })
      );
    }
    new import_obsidian5.Setting(this.contentEl).setName("This is a new device").addButton(
      (btn) => btn.setButtonText("Create new identity").setCta().onClick(() => {
        this.close();
        this.onCreateNew();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};
function automaticIdentityNotice(identity) {
  new import_obsidian5.Notice(
    `Trace will write as "${identity.actorName}". Rename it in Trace settings if you want.`
  );
}

// src/settings.ts
var import_obsidian6 = require("obsidian");
var DEFAULT_SETTINGS = {
  tracesFolder: "Traces",
  explicitPaths: [],
  useFrontmatterFlag: true,
  enforcementMode: "enforce",
  displayTemplate: DEFAULT_TEMPLATE,
  tagSet: ["note", "agent", "decision", "milestone"],
  readOnlyGuard: true,
  rotationMode: "auto",
  rotationMaxBytes: 1e6,
  rotationMaxAgeDays: 365,
  retentionMaxAgeDays: 0,
  retentionMaxBytes: 0
};
var TAG_TOKEN_RE = /^[a-z0-9][a-z0-9_-]*$/;
var TraceSettingTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const identity = this.plugin.identity.get();
    new import_obsidian6.Setting(containerEl).setName("This device's name").setDesc(
      identity ? `Entries from this device are attributed to "${identity.actorName}" (file segment "${identity.actorSlug}"). Existing owned files continue to receive appends after a rename; new writer files use the new name.` : "Trace creates an automatic device name on first use. Set a custom name only if you want one."
    ).addButton(
      (btn) => btn.setButtonText(identity ? "Rename" : "Set custom name").onClick(() => this.plugin.promptDeviceName(() => this.display()))
    );
    new import_obsidian6.Setting(containerEl).setName("Traces folder").setDesc("Folder that holds trace files; new traces are created here.").addText(
      (text) => text.setPlaceholder("Traces").setValue(this.plugin.settings.tracesFolder).onChange(async (value) => {
        this.plugin.settings.tracesFolder = value.replace(/^\/+|\/+$/g, "") || "Traces";
        await this.plugin.saveSettings();
        this.plugin.registry.rebuild();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Rotation").setDesc(
      "Auto starts a new segment when this writer's file reaches the size or age limit. Never keeps one file per writer."
    ).addDropdown(
      (dropdown) => dropdown.addOption("auto", "Auto").addOption("never", "Never").setValue(this.plugin.settings.rotationMode).onChange(async (value) => {
        this.plugin.settings.rotationMode = value === "never" ? "never" : "auto";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Max segment size").setDesc("Auto-rotation size limit in megabytes. Default: 1 megabyte.").addText(
      (text) => text.setPlaceholder("1").setValue(String(this.plugin.settings.rotationMaxBytes / 1e6)).onChange(async (value) => {
        const mb = Number(value.trim());
        if (!Number.isFinite(mb) || mb <= 0) {
          new import_obsidian6.Notice("Max segment size must be a positive number.");
          return;
        }
        this.plugin.settings.rotationMaxBytes = Math.round(mb * 1e6);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Max segment age").setDesc("Auto-rotation age limit in days. Default: 365 days.").addText(
      (text) => text.setPlaceholder("365").setValue(String(this.plugin.settings.rotationMaxAgeDays)).onChange(async (value) => {
        const days = Number(value.trim());
        if (!Number.isFinite(days) || days <= 0) {
          new import_obsidian6.Notice("Max segment age must be a positive number of days.");
          return;
        }
        this.plugin.settings.rotationMaxAgeDays = Math.round(days);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Retention age").setDesc(
      "Move trace files older than this many days to trash during verification. Leave blank to keep forever."
    ).addText(
      (text) => text.setPlaceholder("Forever").setValue(
        this.plugin.settings.retentionMaxAgeDays === 0 ? "" : String(this.plugin.settings.retentionMaxAgeDays)
      ).onChange(async (value) => {
        const trimmed = value.trim();
        if (trimmed === "") {
          this.plugin.settings.retentionMaxAgeDays = 0;
          await this.plugin.saveSettings();
          return;
        }
        const days = Number(trimmed);
        if (!Number.isFinite(days) || days <= 0) {
          new import_obsidian6.Notice("Retention age must be blank or a positive number of days.");
          return;
        }
        this.plugin.settings.retentionMaxAgeDays = Math.round(days);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Retention size").setDesc(
      "Move oldest trace files to trash until total trace storage is under this many megabytes. Leave blank for infinite."
    ).addText(
      (text) => text.setPlaceholder("Infinite").setValue(
        this.plugin.settings.retentionMaxBytes === 0 ? "" : String(this.plugin.settings.retentionMaxBytes / 1e6)
      ).onChange(async (value) => {
        const trimmed = value.trim();
        if (trimmed === "") {
          this.plugin.settings.retentionMaxBytes = 0;
          await this.plugin.saveSettings();
          return;
        }
        const mb = Number(trimmed);
        if (!Number.isFinite(mb) || mb <= 0) {
          new import_obsidian6.Notice("Retention size must be blank or a positive number of megabytes.");
          return;
        }
        this.plugin.settings.retentionMaxBytes = Math.round(mb * 1e6);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Additional trace paths").setDesc("Files outside the folder to treat as traces, one path per line.").addTextArea(
      (text) => text.setPlaceholder("Logs/deploys.laptop.md").setValue(this.plugin.settings.explicitPaths.join("\n")).onChange(async (value) => {
        this.plugin.settings.explicitPaths = value.split("\n").map((line) => line.trim()).filter((line) => line.length > 0);
        await this.plugin.saveSettings();
        this.plugin.registry.rebuild();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Detect traces by frontmatter").setDesc("Treat any note with `trace: true` frontmatter as a trace file.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.useFrontmatterFlag).onChange(async (value) => {
        this.plugin.settings.useFrontmatterFlag = value;
        await this.plugin.saveSettings();
        this.plugin.registry.rebuild();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Enforcement mode").setDesc(
      "Enforce reverts non-append changes to this device's own files; warn only notifies. Other writers' files are never reverted either way."
    ).addDropdown(
      (dropdown) => dropdown.addOption("enforce", "Enforce (revert and notify)").addOption("warn", "Warn only").setValue(this.plugin.settings.enforcementMode).onChange(async (value) => {
        this.plugin.settings.enforcementMode = value === "warn" ? "warn" : "enforce";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Read-only guard in the editor").setDesc(
      "Block edits to committed entries in the editor. Off still leaves the modify-time protection active."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.readOnlyGuard).onChange(async (value) => {
        this.plugin.settings.readOnlyGuard = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Display template").setDesc(
      "Decoration for reading view only \u2014 files always keep the canonical format. All placeholders required, in order: {{seq}} {{timestamp}} {{actor}} {{tag}} {{text}} {{hash}}."
    ).addTextArea(
      (text) => text.setValue(this.plugin.settings.displayTemplate).onChange(async (value) => {
        const error = validateTemplate(value);
        if (error) {
          new import_obsidian6.Notice(`Template not saved: ${error}`);
          return;
        }
        this.plugin.settings.displayTemplate = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Tags").setDesc(
      "Tags offered when appending, comma-separated, lowercase letters/digits/-/_ (no #). Reserved protocol tags are not allowed."
    ).addText(
      (text) => text.setValue(this.plugin.settings.tagSet.join(", ")).onChange(async (value) => {
        const tokens = value.split(",").map((t) => t.trim().replace(/^#/, "")).filter((t) => t.length > 0);
        const bad = tokens.filter((t) => !TAG_TOKEN_RE.test(t));
        if (bad.length > 0) {
          new import_obsidian6.Notice(`Invalid tag${bad.length > 1 ? "s" : ""}: ${bad.join(", ")}`);
          return;
        }
        const reserved = tokens.filter(
          (t) => RESERVED_TAGS.includes("#" + t)
        );
        if (reserved.length > 0) {
          new import_obsidian6.Notice(`Reserved tag${reserved.length > 1 ? "s" : ""}: ${reserved.join(", ")}`);
          return;
        }
        this.plugin.settings.tagSet = tokens;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/verify.ts
var import_obsidian7 = require("obsidian");
async function verifyFile(plugin, file) {
  const content = await plugin.app.vault.read(file);
  const result = await verifyTrace(content);
  const meta = plugin.registry.get(file.path);
  const identity = plugin.identity.get();
  const own = meta !== null && identity !== null && meta.actorId === identity.actorId;
  const state = plugin.chain.get(file.path);
  let stateCheck;
  if (!state) {
    stateCheck = {
      code: "none",
      message: "No recorded head on this device yet."
    };
    if (result.ok && result.headHash !== null) {
      await adoptState(plugin, file.path, content, result);
      stateCheck = { code: "adopted", message: "Recorded as trusted head." };
    }
  } else if (result.ok && result.headHash !== null) {
    const lastSeq = result.entries[result.entries.length - 1].seq;
    if (lastSeq < state.seq) {
      stateCheck = {
        code: "behind",
        message: `File ends at seq ${lastSeq} but seq ${state.seq} was recorded \u2014 entries removed from the end, or sync has not delivered them yet.`
      };
    } else if (result.entries[state.seq - 1] && result.entries[state.seq - 1].fullHash !== state.head) {
      stateCheck = {
        code: "diverged",
        message: `Entry ${state.seq} no longer matches the recorded head \u2014 content was replaced and re-chained outside the append path.`
      };
    } else {
      await adoptState(plugin, file.path, content, result);
      stateCheck = { code: "ok", message: "Matches the recorded head." };
    }
  } else {
    stateCheck = {
      code: "none",
      message: "Chain invalid; recorded head left untouched."
    };
  }
  if (result.ok && stateCheck.code !== "behind" && stateCheck.code !== "diverged") {
    plugin.guard.suspect.delete(file.path);
  }
  return { path: file.path, meta, own, result, stateCheck };
}
async function adoptState(plugin, path, content, result) {
  const last = result.entries[result.entries.length - 1];
  if (!last || last.fullHash === null) return;
  await plugin.chain.set(path, {
    seq: last.seq,
    head: last.fullHash,
    entryCount: result.entryCount,
    contentSha: await sha256Hex(content),
    updatedAt: nowTimestamp()
  });
}
function formatBytes(bytes) {
  if (bytes < 1e6) return `${Math.round(bytes / 1e3)} KB`;
  return `${(bytes / 1e6).toFixed(1)} MB`;
}
async function applyRetention(plugin, files, logical) {
  const { retentionMaxAgeDays, retentionMaxBytes } = plugin.settings;
  const removals = /* @__PURE__ */ new Map();
  const mark = (file, reason) => {
    const existing = removals.get(file.path) ?? { file: file.file, reasons: [] };
    existing.reasons.push(reason);
    removals.set(file.path, existing);
  };
  if (retentionMaxAgeDays > 0) {
    const now = Date.now();
    const maxAgeMs = retentionMaxAgeDays * 24 * 60 * 60 * 1e3;
    for (const file of files) {
      if (now - file.mtime > maxAgeMs) {
        const ageDays = Math.floor((now - file.mtime) / (24 * 60 * 60 * 1e3));
        mark(file, `${ageDays} days old, beyond the ${retentionMaxAgeDays}-day limit`);
      }
    }
  }
  if (retentionMaxBytes > 0) {
    let total = files.reduce((sum, file) => sum + file.size, 0);
    const alreadyMarkedSize = [...removals.keys()].reduce((sum, path) => {
      const file = files.find((candidate) => candidate.path === path);
      return sum + (file?.size ?? 0);
    }, 0);
    total -= alreadyMarkedSize;
    for (const file of files.filter((candidate) => !removals.has(candidate.path)).sort((a, b) => a.mtime - b.mtime)) {
      if (total <= retentionMaxBytes) break;
      mark(
        file,
        `total trace storage exceeds ${formatBytes(retentionMaxBytes)}`
      );
      total -= file.size;
    }
  }
  for (const [path, removal] of removals) {
    plugin.guard.dropPath(path);
    await plugin.chain.remove(path);
    await plugin.app.fileManager.trashFile(removal.file);
    logical.push(
      `Retention removed "${path}" (${removal.reasons.join("; ")}).`
    );
  }
  if (removals.size > 0) plugin.registry.rebuild();
}
async function verifyAllTraces(plugin) {
  const files = [];
  const logical = [];
  const byTrace = /* @__PURE__ */ new Map();
  const retentionFiles = [];
  for (const [path, meta] of plugin.registry.all()) {
    const file = plugin.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian7.TFile)) continue;
    retentionFiles.push({
      path,
      file,
      size: file.stat.size,
      mtime: file.stat.mtime
    });
    const report = await verifyFile(plugin, file);
    files.push(report);
    if (meta) {
      const group = byTrace.get(meta.traceSlug) ?? [];
      group.push(report);
      byTrace.set(meta.traceSlug, group);
    }
  }
  for (const [slug, group] of byTrace) {
    const names = new Set(group.map((r) => r.meta?.traceName));
    if (names.size > 1) {
      logical.push(
        `Trace "${slug}": files disagree on the trace name (${[...names].join(", ")}).`
      );
    }
    const byActor = /* @__PURE__ */ new Map();
    for (const r of group) {
      if (!r.meta) continue;
      byActor.set(r.meta.actorId, (byActor.get(r.meta.actorId) ?? 0) + 1);
    }
    for (const [actorId, count] of byActor) {
      if (count > 1) {
        const actorNames = group.filter((r) => r.meta?.actorId === actorId).map((r) => r.meta?.actorName).join(", ");
        logical.push(
          `Trace "${slug}": writer id ${actorId} appears in ${count} files (${actorNames}) \u2014 likely a renamed device; older files stay valid but no longer grow.`
        );
      }
    }
    for (const r of group) {
      if (!r.meta) continue;
      const info = parseTracePath(r.path, plugin.settings.tracesFolder);
      if (info) {
        if (info.traceSlug !== r.meta.traceSlug || info.actorSlug !== r.meta.actorSlug) {
          logical.push(
            `File "${r.path}" does not match its trace or actor frontmatter.`
          );
        }
        continue;
      }
      const basename = r.path.split("/").pop();
      const expectedName = traceFileName(r.meta.traceSlug, r.meta.actorSlug);
      if (basename !== expectedName) {
        logical.push(
          `File "${r.path}" should be named "${expectedName}" to match its frontmatter.`
        );
      }
    }
  }
  const orphanedStates = plugin.chain.paths().filter(
    (path) => !(plugin.app.vault.getAbstractFileByPath(path) instanceof import_obsidian7.TFile)
  );
  for (const path of orphanedStates) {
    logical.push(
      `Recorded trace "${path}" no longer exists on disk \u2014 deleted or moved outside Obsidian.`
    );
  }
  await applyRetention(plugin, retentionFiles, logical);
  return { files, logical, orphanedStates };
}
async function rebaseline(plugin, file) {
  const meta = plugin.registry.get(file.path);
  const identity = plugin.identity.get();
  if (!meta || !identity || meta.actorId !== identity.actorId) {
    throw new Error("Only this device's own trace files can be re-baselined");
  }
  const content = await plugin.app.vault.read(file);
  const parsed = parseTrace(content);
  const badLines = parsed.issues.filter((i) => i.code === "BAD_LINE");
  if (badLines.length > 0) {
    throw new Error(
      `Line ${badLines[0].line} is not a parseable entry \u2014 repair or remove unparseable lines first`
    );
  }
  const fmEnd = content.indexOf("\n---\n");
  if (!content.startsWith("---\n") || fmEnd === -1) {
    throw new Error("File is missing its frontmatter");
  }
  const frontmatterBlock = content.slice(0, fmEnd + 5);
  let head = GENESIS;
  const lines = [];
  let seq = 0;
  for (const entry of parsed.entries) {
    seq += 1;
    const fields = {
      seq,
      timestamp: entry.timestamp,
      actor: entry.actor,
      tag: entry.tag,
      text: entry.text
    };
    head = await computeEntryHash(head, fields);
    lines.push(formatEntryLine(fields, head));
  }
  seq += 1;
  const marker = {
    seq,
    timestamp: nowTimestamp(),
    actor: meta.actorName,
    tag: "#rebaseline",
    text: "Re-baseline: current content accepted as the new trusted state"
  };
  head = await computeEntryHash(head, marker);
  lines.push(formatEntryLine(marker, head));
  const newContent = frontmatterBlock + lines.join("\n") + "\n";
  await plugin.writer.replaceContent(file, newContent, {
    seq,
    head,
    entryCount: seq,
    contentSha: await sha256Hex(newContent),
    updatedAt: nowTimestamp()
  });
  plugin.guard.suspect.delete(file.path);
}
var ConfirmModal = class extends import_obsidian7.Modal {
  constructor(app, title, body, confirmLabel, onConfirm) {
    super(app);
    this.title = title;
    this.body = body;
    this.confirmLabel = confirmLabel;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    this.setTitle(this.title);
    this.contentEl.createEl("p", { text: this.body });
    new import_obsidian7.Setting(this.contentEl).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => this.close())
    ).addButton(
      (btn) => btn.setButtonText(this.confirmLabel).setWarning().onClick(() => {
        this.close();
        this.onConfirm();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};
function issueLabel(issue) {
  const where = issue.seq !== void 0 ? `entry ${issue.seq} (line ${issue.line})` : issue.line > 0 ? `line ${issue.line}` : "file";
  return `${where}: ${issue.message}`;
}
var VerifyResultsModal = class extends import_obsidian7.Modal {
  constructor(plugin, report, heading) {
    super(plugin.app);
    this.plugin = plugin;
    this.report = report;
    this.heading = heading;
  }
  onOpen() {
    this.setTitle(this.heading);
    this.render();
  }
  render() {
    const root = this.contentEl;
    root.empty();
    if (this.report.files.length === 0 && this.report.logical.length === 0) {
      root.createEl("p", { text: "No trace files found." });
      return;
    }
    for (const fileReport of this.report.files) {
      const section = root.createDiv({ cls: "trace-verify-file" });
      const ok = fileReport.result.ok && fileReport.stateCheck.code !== "behind" && fileReport.stateCheck.code !== "diverged";
      const title = section.createDiv({ cls: "trace-verify-title" });
      title.createSpan({
        cls: ok ? "trace-verify-ok" : "trace-verify-fail",
        text: ok ? "OK" : "Check"
      });
      title.createSpan({
        text: ` ${fileReport.path}${fileReport.own ? " (this device)" : ""}`
      });
      const detail = section.createEl("ul", { cls: "trace-verify-detail" });
      if (fileReport.result.ok) {
        const head = fileReport.result.headHash;
        detail.createEl("li", {
          text: `${fileReport.result.entryCount} entries verified; head ${head ? "#" + head.slice(0, 8) : "n/a"}.`
        });
      }
      for (const issue of fileReport.result.issues) {
        detail.createEl("li", { text: issueLabel(issue) });
      }
      for (const issue of fileReport.result.conventionIssues) {
        detail.createEl("li", {
          text: `Convention issue at entry ${issue.seq ?? "?"}: ${issue.message}`
        });
      }
      if (fileReport.stateCheck.code === "behind" || fileReport.stateCheck.code === "diverged") {
        detail.createEl("li", { text: fileReport.stateCheck.message });
      }
      if (!ok && fileReport.own) {
        new import_obsidian7.Setting(section).addButton(
          (btn) => btn.setButtonText("Re-baseline\u2026").setWarning().onClick(() => this.confirmRebaseline(fileReport.path))
        );
      }
      if (!ok && !fileReport.own) {
        detail.createEl("li", {
          text: "This file belongs to another device; re-baseline it there if its content is correct."
        });
      }
    }
    if (this.report.logical.length > 0) {
      root.createEl("h3", { text: "Trace-level checks" });
      const list = root.createEl("ul");
      for (const item of this.report.logical) {
        list.createEl("li", { text: item });
      }
    }
    for (const path of this.report.orphanedStates) {
      new import_obsidian7.Setting(root).setName(`Forget recorded state for "${path}"`).setDesc("Only do this if the deletion was intentional.").addButton(
        (btn) => btn.setButtonText("Forget").onClick(() => {
          void this.plugin.chain.remove(path).then(() => {
            this.report.orphanedStates = this.report.orphanedStates.filter((p) => p !== path);
            this.report.logical = this.report.logical.filter(
              (l) => !l.includes(`"${path}"`)
            );
            this.render();
          });
        })
      );
    }
  }
  confirmRebaseline(path) {
    new ConfirmModal(
      this.app,
      "Re-baseline this trace file?",
      "The current content becomes the new trusted state: sequence numbers are renumbered, every anchor hash is recomputed, and a #rebaseline entry is appended. Anchors that external tools recorded before this point will no longer verify.",
      "Re-baseline",
      () => {
        const file = this.plugin.app.vault.getAbstractFileByPath(path);
        if (!(file instanceof import_obsidian7.TFile)) return;
        void rebaseline(this.plugin, file).then(async () => {
          new import_obsidian7.Notice(`Re-baselined "${path}".`);
          const fresh = await verifyFile(this.plugin, file);
          this.report.files = this.report.files.map(
            (r) => r.path === path ? fresh : r
          );
          this.render();
        }).catch((error) => {
          new import_obsidian7.Notice(
            `Re-baseline failed: ${error instanceof Error ? error.message : String(error)}`
          );
        });
      }
    ).open();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var TraceRegistry = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.files = /* @__PURE__ */ new Map();
  }
  rebuild() {
    const { app, settings } = this.plugin;
    this.files.clear();
    for (const file of app.vault.getMarkdownFiles()) {
      const inFolder = parseTracePath(file.path, settings.tracesFolder) !== null;
      const explicit = settings.explicitPaths.includes(file.path);
      const fm = app.metadataCache.getFileCache(file)?.frontmatter;
      const flagged = settings.useFrontmatterFlag && fm?.["trace"] === true;
      if (!inFolder && !explicit && !flagged) continue;
      if (fm?.["trace"] !== true) continue;
      this.files.set(file.path, metaFromFrontmatter(fm));
    }
  }
  isTrace(path) {
    return this.files.has(path);
  }
  /** Complete metadata for a trace file, or null (not a trace, or its
   * frontmatter is incomplete — verification reports the latter). */
  get(path) {
    return this.files.get(path) ?? null;
  }
  all() {
    return this.files;
  }
  /** Distinct logical traces across all writer files. */
  logicalTraces() {
    const bySlug = /* @__PURE__ */ new Map();
    for (const meta of this.files.values()) {
      if (!meta) continue;
      if (!bySlug.has(meta.traceSlug)) {
        bySlug.set(meta.traceSlug, meta.traceName);
      }
    }
    return [...bySlug.entries()].map(([slug, name]) => ({ slug, name })).sort((a, b) => a.name.localeCompare(b.name));
  }
  /** Distinct writers seen in trace files, keyed by actor id. */
  uniqueActors() {
    const byId = /* @__PURE__ */ new Map();
    for (const meta of this.files.values()) {
      if (meta && !byId.has(meta.actorId)) byId.set(meta.actorId, meta);
    }
    return [...byId.values()];
  }
  /** This device's current writer file for a logical trace, wherever it lives. */
  ownFileFor(traceSlug, identity) {
    const candidates = [];
    for (const [path, meta] of this.files) {
      if (meta && meta.traceSlug === traceSlug && meta.actorId === identity.actorId) {
        candidates.push(path);
      }
    }
    candidates.sort(
      (a, b) => tracePathOrder(b, this.plugin.settings.tracesFolder) - tracePathOrder(a, this.plugin.settings.tracesFolder) || b.localeCompare(a)
    );
    return candidates[0] ?? null;
  }
  nextSegmentFor(traceSlug, actorSlug) {
    let max = 0;
    for (const path of this.files.keys()) {
      const info = parseTracePath(path, this.plugin.settings.tracesFolder);
      if (info && !info.legacy && info.traceSlug === traceSlug && info.actorSlug === actorSlug) {
        max = Math.max(max, info.segment ?? 0);
      }
    }
    return max + 1;
  }
};
var TracePlugin = class extends import_obsidian8.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
  }
  async onload() {
    const data = await this.loadData() ?? {};
    this.settings = { ...DEFAULT_SETTINGS, ...data.settings };
    this.lastUsedTrace = data.lastUsedTrace;
    this.identity = new IdentityManager(this.app);
    this.identity.load();
    this.chain = new ChainStore(() => this.savePluginData());
    this.chain.loadFrom(data.chainState);
    this.registry = new TraceRegistry(this);
    this.guard = new TraceGuard({
      app: this.app,
      getSettings: () => this.settings,
      getIdentity: () => this.identity.get(),
      getMeta: (path) => this.registry.get(path),
      chain: this.chain,
      writer: null
    });
    this.writer = new TraceWriter({
      app: this.app,
      chain: this.chain,
      markSelfWrite: (path) => this.guard.markSelfWrite(path),
      setCache: (path, content) => this.guard.setCache(path, content)
    });
    this.guard.setWriter(this.writer);
    this.addSettingTab(new TraceSettingTab(this.app, this));
    this.registerCommands();
    this.registerEditorExtension(
      buildEditorGuard(
        {
          app: this.app,
          getSettings: () => this.settings,
          getIdentity: () => this.identity.get(),
          getMeta: (path) => this.registry.get(path),
          chain: this.chain,
          writer: this.writer
        },
        this.guard
      )
    );
    this.registerPostProcessor();
    this.registerVaultEvents();
    this.app.workspace.onLayoutReady(() => {
      void this.initAfterLayout();
    });
  }
  onunload() {
    this.guard.dispose();
  }
  async initAfterLayout() {
    this.registry.rebuild();
    if (!this.identity.get()) {
      const actors = this.registry.uniqueActors();
      if (actors.length > 0) {
        this.promptIdentityRecovery();
      } else {
        automaticIdentityNotice(this.identity.createDefault());
      }
    }
    await this.guard.warmCache([...this.registry.all().keys()]);
  }
  registerCommands() {
    this.addRibbonIcon("list-plus", "Append entry", () => {
      new AppendEntryModal(this).open();
    });
    this.addCommand({
      id: "append-entry",
      name: "Append entry",
      callback: () => new AppendEntryModal(this).open()
    });
    this.addCommand({
      id: "create-timeline",
      name: "Create timeline",
      callback: () => new CreateTraceModal(this).open()
    });
    this.addCommand({
      id: "record-file-change",
      name: "Record file change",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file) return false;
        if (!checking) new RecordFileChangeModal(this, file).open();
        return true;
      }
    });
    this.addCommand({
      id: "verify-file",
      name: "Verify integrity",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file || !this.registry.isTrace(file.path)) return false;
        if (!checking) {
          void verifyFile(this, file).then((report) => {
            new VerifyResultsModal(
              this,
              { files: [report], logical: [], orphanedStates: [] },
              `Verify: ${file.name}`
            ).open();
          });
        }
        return true;
      }
    });
    this.addCommand({
      id: "verify-all",
      name: "Verify all",
      callback: () => {
        void verifyAllTraces(this).then((report) => {
          new VerifyResultsModal(this, report, "Verify all").open();
        });
      }
    });
    this.addCommand({
      id: "rebaseline-file",
      name: "Re-baseline file",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        const identity = this.identity.get();
        const meta = file ? this.registry.get(file.path) : null;
        const own = !!meta && !!identity && meta.actorId === identity.actorId;
        if (!file || !own) return false;
        if (!checking) {
          new ConfirmModal(
            this.app,
            "Re-baseline this trace file?",
            "The current content becomes the new trusted state: sequence numbers are renumbered, every anchor hash is recomputed, and a #rebaseline entry is appended. Anchors recorded by external tools before this point will no longer verify.",
            "Re-baseline",
            () => {
              void rebaseline(this, file).then(() => new import_obsidian8.Notice(`Re-baselined "${file.path}".`)).catch(
                (error) => new import_obsidian8.Notice(
                  `Re-baseline failed: ${error instanceof Error ? error.message : String(error)}`
                )
              );
            }
          ).open();
        }
        return true;
      }
    });
  }
  registerVaultEvents() {
    const rebuild = (0, import_obsidian8.debounce)(() => this.registry.rebuild(), 300, true);
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian8.TFile) this.guard.onModify(file);
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian8.TFile) {
          this.guard.onRename(file, oldPath);
          rebuild();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        this.guard.onDelete(file.path);
        rebuild();
      })
    );
    this.registerEvent(
      this.app.vault.on("create", () => rebuild())
    );
    this.registerEvent(
      this.app.metadataCache.on("changed", () => rebuild())
    );
  }
  registerPostProcessor() {
    this.registerMarkdownPostProcessor((el, ctx) => {
      if (!this.registry.isTrace(ctx.sourcePath)) return;
      el.querySelectorAll("li").forEach((li) => {
        const entry = parseEntryLine("- " + (li.textContent ?? "").trim());
        if (!entry) return;
        li.empty();
        li.addClass("trace-entry");
        const segments = renderTemplateSegments(
          this.settings.displayTemplate,
          entry
        );
        for (const segment of segments) {
          if (segment.value === "") continue;
          li.createSpan({
            cls: segment.kind === "literal" ? "trace-literal" : "trace-" + segment.kind,
            text: segment.value
          });
        }
      });
    });
  }
  // --- Actions ------------------------------------------------------------
  promptIdentityRecovery(onDone) {
    new ReclaimIdentityModal(
      this.app,
      this.registry.uniqueActors(),
      (meta) => {
        this.identity.reclaim(meta);
        new import_obsidian8.Notice(`This device now writes as "${meta.actorName}".`);
        onDone?.();
      },
      () => {
        automaticIdentityNotice(this.identity.createDefault());
        onDone?.();
      }
    ).open();
  }
  identityForWrite(onReady) {
    const current = this.identity.get();
    if (current) return current;
    if (this.registry.uniqueActors().length > 0) {
      this.promptIdentityRecovery(onReady);
      return null;
    }
    const identity = this.identity.createDefault();
    automaticIdentityNotice(identity);
    return identity;
  }
  nextSegmentPath(traceSlug, actorSlug) {
    return traceSegmentPath(
      this.settings.tracesFolder,
      traceSlug,
      this.registry.nextSegmentFor(traceSlug, actorSlug),
      currentSegmentMonth(),
      actorSlug
    );
  }
  shouldRotate(file) {
    if (this.settings.rotationMode === "never") return false;
    if (file.stat.size >= this.settings.rotationMaxBytes) return true;
    const maxAgeMs = this.settings.rotationMaxAgeDays * 24 * 60 * 60 * 1e3;
    return Date.now() - file.stat.ctime >= maxAgeMs;
  }
  async rotateTraceFile(file, meta) {
    const content = await this.app.vault.read(file);
    const result = await verifyTrace(content);
    if (!result.ok || result.headHash === null) {
      throw new AppendBlockedError(
        `"${file.path}" must verify before rotation. Run "Verify integrity".`
      );
    }
    const last = result.entries[result.entries.length - 1];
    if (!last) {
      throw new AppendBlockedError(`"${file.path}" has no entries to rotate from.`);
    }
    const path = this.nextSegmentPath(meta.traceSlug, meta.actorSlug);
    const rotated = await this.writer.createTraceFile(this.settings.tracesFolder, meta, {
      path,
      initialFields: {
        seq: 1,
        timestamp: (/* @__PURE__ */ new Date()).toISOString().replace(/\.\d{3}Z$/, "Z"),
        actor: meta.actorName,
        tag: "#rotate",
        text: formatRotationPayload({
          previous: file.path,
          previousSeq: last.seq,
          previousHead: result.headHash
        })
      }
    });
    this.registry.rebuild();
    new import_obsidian8.Notice(`Rotated trace segment to "${rotated.path}".`);
    return rotated;
  }
  /** Append through the modal path; creates this device's writer file for
   * the logical trace when it does not exist yet. */
  async appendToTrace(traceSlug, traceName, tag, text) {
    const identity = this.identityForWrite(() => {
      void this.appendToTrace(traceSlug, traceName, tag, text);
    });
    if (!identity) return;
    try {
      let path = this.registry.ownFileFor(traceSlug, identity);
      if (path === null) {
        const clash = this.registry.uniqueActors().find(
          (a) => a.actorSlug === identity.actorSlug && a.actorId !== identity.actorId
        );
        if (clash) {
          new import_obsidian8.Notice(
            `This device's name "${identity.actorName}" collides with writer "${clash.actorName}" (both use "${identity.actorSlug}"). Rename this device in Trace settings first.`
          );
          return;
        }
        const created = await this.writer.createTraceFile(
          this.settings.tracesFolder,
          {
            traceName,
            traceSlug,
            actorName: identity.actorName,
            actorSlug: identity.actorSlug,
            actorId: identity.actorId
          },
          { path: this.nextSegmentPath(traceSlug, identity.actorSlug) }
        );
        this.registry.rebuild();
        path = created.path;
      }
      const found = this.app.vault.getAbstractFileByPath(path);
      if (!(found instanceof import_obsidian8.TFile)) {
        new import_obsidian8.Notice(`Trace file "${path}" is missing.`);
        return;
      }
      let file = found;
      const meta = this.registry.get(path) ?? {
        traceName,
        traceSlug,
        actorName: identity.actorName,
        actorSlug: identity.actorSlug,
        actorId: identity.actorId
      };
      if (this.shouldRotate(file)) {
        file = await this.rotateTraceFile(file, meta);
      }
      const appended = await this.writer.appendEntry(file, meta, {
        tag,
        text
      });
      this.lastUsedTrace = traceSlug;
      await this.savePluginData();
      new import_obsidian8.Notice(
        `Appended entry ${appended.seq} (#${appended.anchor}) to "${traceName}".`
      );
    } catch (error) {
      if (error instanceof AppendBlockedError) {
        new import_obsidian8.Notice(`Append blocked: ${error.message}`, 1e4);
      } else {
        new import_obsidian8.Notice(
          `Append failed: ${error instanceof Error ? error.message : String(error)}`
        );
      }
    }
  }
  /** Create a new logical trace (this device's file with genesis). */
  async createTrace(name, slug) {
    const identity = this.identityForWrite(() => {
      void this.createTrace(name, slug);
    });
    if (!identity) return;
    if (this.registry.ownFileFor(slug, identity)) {
      new import_obsidian8.Notice(`This device already has a file for trace "${name}".`);
      return;
    }
    try {
      const file = await this.writer.createTraceFile(
        this.settings.tracesFolder,
        {
          traceName: name,
          traceSlug: slug,
          actorName: identity.actorName,
          actorSlug: identity.actorSlug,
          actorId: identity.actorId
        },
        { path: this.nextSegmentPath(slug, identity.actorSlug) }
      );
      this.registry.rebuild();
      this.lastUsedTrace = slug;
      await this.savePluginData();
      new import_obsidian8.Notice(`Created trace "${name}" (${file.path}).`);
      await this.app.workspace.getLeaf(false).openFile(file);
    } catch (error) {
      new import_obsidian8.Notice(
        `Create failed: ${error instanceof Error ? error.message : String(error)}`
      );
    }
  }
  /** Set or rename this device's writer name (device-local storage). */
  promptDeviceName(onDone) {
    const current = this.identity.get();
    const others = this.registry.uniqueActors().filter((a) => a.actorId !== current?.actorId).map((a) => ({ actorSlug: a.actorSlug, actorName: a.actorName }));
    new DeviceNameModal(
      this.app,
      others,
      (name) => {
        if (current) {
          this.identity.save({
            actorId: current.actorId,
            actorName: name,
            actorSlug: slugify(name)
          });
          new import_obsidian8.Notice(
            `This device now writes as "${name}". Existing owned files continue to receive appends; new writer files use *.${slugify(name)}.md.`
          );
        } else {
          this.identity.create(name);
          new import_obsidian8.Notice(`This device writes as "${name}".`);
        }
        onDone?.();
      },
      current?.actorName ?? ""
    ).open();
  }
  async saveSettings() {
    await this.savePluginData();
  }
  async savePluginData() {
    const data = {
      settings: this.settings,
      chainState: this.chain.snapshot(),
      lastUsedTrace: this.lastUsedTrace
    };
    await this.saveData(data);
  }
};
